allauth/account/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^signup/$", views.signup, name="account_signup"),
    url(r"^login/$", views.login, name="account_login"),
    url(r"^logout/$", views.logout, name="account_logout"),

    url(r"^password/change/$", views.password_change,
        name="account_change_password"),
    url(r"^password/set/$", views.password_set, name="account_set_password"),

    url(r"^inactive/$", views.account_inactive, name="account_inactive"),

    # E-mail
    url(r"^email/$", views.email, name="account_email"),
    url(r"^confirm-email/$", views.email_verification_sent,
        name="account_email_verification_sent"),
    url(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
        name="account_confirm_email"),

    # password reset
    url(r"^password/reset/$", views.password_reset,
        name="account_reset_password"),
    url(r"^password/reset/done/$", views.password_reset_done,
        name="account_reset_password_done"),
    url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        views.password_reset_from_key,
        name="account_reset_password_from_key"),
    url(r"^password/reset/key/done/$", views.password_reset_from_key_done,
        name="account_reset_password_from_key_done"),
]

allauth/socialaccount/providers/amazon/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import AmazonProvider

urlpatterns = default_urlpatterns(AmazonProvider)

allauth/socialaccount/providers/asana/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import AsanaProvider

urlpatterns = default_urlpatterns(AsanaProvider)

allauth/socialaccount/providers/baidu/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BaiduProvider

urlpatterns = default_urlpatterns(BaiduProvider)

allauth/socialaccount/providers/bitly/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import BitlyProvider

urlpatterns = default_urlpatterns(BitlyProvider)

allauth/socialaccount/providers/douban/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DoubanProvider

urlpatterns = default_urlpatterns(DoubanProvider)

allauth/socialaccount/providers/edmodo/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import EdmodoProvider

urlpatterns = default_urlpatterns(EdmodoProvider)

allauth/socialaccount/providers/fxa/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import FirefoxAccountsProvider

urlpatterns = default_urlpatterns(FirefoxAccountsProvider)

allauth/socialaccount/providers/hubic/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import HubicProvider

urlpatterns = default_urlpatterns(HubicProvider)

allauth/socialaccount/providers/oauth/urls.py
from django.conf.urls import url, include
from allauth.utils import import_attribute


def default_urlpatterns(provider):
    login_view = import_attribute(
        provider.get_package() + '.views.oauth_login')
    callback_view = import_attribute(
        provider.get_package() + '.views.oauth_callback')

    urlpatterns = [
        url('^login/$',
            login_view, name=provider.id + "_login"),
        url('^login/callback/$', callback_view,
            name=provider.id + "_callback"),
    ]

    return [url('^' + provider.get_slug() + '/', include(urlpatterns))]

allauth/socialaccount/providers/orcid/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import OrcidProvider

urlpatterns = default_urlpatterns(OrcidProvider)

allauth/socialaccount/providers/slack/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import SlackProvider

urlpatterns = default_urlpatterns(SlackProvider)

allauth/socialaccount/providers/vimeo/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns
from .provider import VimeoProvider

urlpatterns = default_urlpatterns(VimeoProvider)

allauth/socialaccount/providers/vk/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from .provider import VKProvider

urlpatterns = default_urlpatterns(VKProvider)

allauth/socialaccount/providers/weibo/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import WeiboProvider

urlpatterns = default_urlpatterns(WeiboProvider)

allauth/socialaccount/providers/xing/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns
from .provider import XingProvider

urlpatterns = default_urlpatterns(XingProvider)

allauth/socialaccount/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^login/cancelled/$', views.login_cancelled,
        name='socialaccount_login_cancelled'),
    url('^login/error/$', views.login_error, name='socialaccount_login_error'),
    url('^signup/$', views.signup, name='socialaccount_signup'),
    url('^connections/$', views.connections, name='socialaccount_connections')
]

allauth/urls.py
from django.conf.urls import url, include
from allauth.compat import importlib

from allauth.socialaccount import providers

from . import app_settings

urlpatterns = [url('^', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [url('^social/', include('allauth.socialaccount.urls'))]

for provider in providers.registry.get_list():
    try:
        prov_mod = importlib.import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

appointment/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^book/$', views.book_appointment, name='book_appointment'),
    url(r'^book/detail/(?P<pk>\d+)/$', views.book_detail, name='book_detail'),
    url(r'^book/success/$', views.booking_success, name='booking_success'),
    url(r'^bookings/$', views.bookings, name='bookings'),
]

cars/urls.py
from django.conf.urls import url

from .views import get_car_model

urlpatterns = [
    url(r'^model/$', get_car_model, name='get_car_model'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from services.views import home, about, contact, profile
import allauth.account.views


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^admin/', admin.site.urls),
    url(r'^cars/', include('cars.urls', namespace='cars')),
    url(r'^services/', include('services.urls', namespace='services')),
    url(r'^appointment/', include('appointment.urls', namespace='appointment')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/login/$', allauth.account.views.login, name='login'),
    url(r'^accounts/logout/$', allauth.account.views.logout, name='logout'),
    url(r'^accounts/signup/$', allauth.account.views.signup, name='signup'),
    url(r'^profile/$', profile, name='profile'),
]

services/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # url(r'^$', views.service_list, name='service_list'),
    url(r'^service/(?P<id>\d+)/$', views.service_detail, name='service_detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Car Dry Cleaning</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

  {% block head %}
  {% endblock head %}

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }
  }
  </style>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Logo</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">

    {% block navbar %}

    {% endblock navbar %}

      <ul class="nav navbar-nav navbar-center">
          <li><a href="#">Call:  +918109883907</a> </li>
          <li><a href="#">Email: info@carservice.com</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="dropdown ">
            <a class="dropdown-toggle " data-toggle="dropdown">
            <span class="glyphicon glyphicon-user "></span>{{ user.username }}
            <span class="caret"></span> </a>
            <ul class="dropdown-menu ">
                <li><a href="{% url 'profile' %}">My profile</a></li>
                <li><a href="{% url 'appointment:bookings' %}">My Bookings</a> </li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out">Logout</span> </a> </li>


            </ul>
          </li>
            <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span>{{ user.username }}</a></li>-->
            <!--<li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out">Logout</span> </a> </li>-->
          {% else %}
            <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>


<div id="myCarousel" class="carousel slide" data-ride="carousel">
    {% block carousel %}
      <br><br>
    {% endblock carousel %}
</div>

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">  <!-- singular -->
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}


<div class="container">


{% block container %}


{% endblock container %}

</div><br>


<footer class="container-fluid text-center">
  <p>Footer Text</p>

  {% block footer %}

  {% endblock footer %}
</footer>

</body>
</html>

templates/home/about.html
{% extends 'home/base.html' %}

{% block navbar %}
 <ul class="nav navbar-nav nav-tabs">
     <li><a href="{% url 'home' %}">Home</a></li>
     <li class="active"><a href="{% url 'about' %}">About</a></li>
     <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" >Services
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          {% for service in services %}
          <li><a href="{{ service.get_absolute_url }}">{{ service.service_name }}</a></li>
          {% empty %}
          <li>Empty</li>
          {% endfor %}
        </ul>
     </li>
     <li><a href="{% url 'contact' %}">Contact Us</a></li>
     <li><a href="{% url 'appointment:book_appointment' %}">Book an Appointment</a></li>
 </ul>
{% endblock navbar %}

templates/home/base.html
{% extends 'base.html' %}



{% block carousel %}

    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://placehold.it/1200x400?text=IMAGE" alt="Image">
        <div class="carousel-caption">
          <h3>Sell $</h3>
          <p>Money Money.</p>
        </div>
      </div>

      <div class="item">
        <img src="http://placehold.it/1200x400?text=Another Image Maybe" alt="Image">
        <div class="carousel-caption">
          <h3>More Sell $</h3>
          <p>Lorem ipsum...</p>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

{% endblock carousel %}


{% block container %}
<div class="header text-center">
 <h3>What We Do</h3><br>
</div>

  <div class="row">
    <div class="col-sm-4">
      <img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Project 1</p>
    </div>
    <div class="col-sm-4">
      <img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Project 2</p>
    </div>
    <div class="col-sm-4">
      <div class="well">
       <p>Some text..</p>
      </div>
      <div class="well">
       <p>Some text..</p>
      </div>
    </div>
  </div>

{% endblock container %}


{% block footer %}
{% endblock footer %}

templates/home/contact.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}



{% block navbar %}
<ul class="nav navbar-nav nav-tabs">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'about' %}">About</a></li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown">Services
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          {% for service in services %}
          <li><a href="{{ service.get_absolute_url }}">{{ service.service_name }}</a></li>
          {% empty %}
          <li>Empty</li>
          {% endfor %}
        </ul>
      </li>
    <li class="active"><a href="{% url 'contact' %}">Contact Us</a></li>
    <li><a href="{% url 'appointment:book_appointment' %}">Book an Appointment</a></li>
</ul>
{% endblock navbar %}


{% block container %}
<div class="row">
    <div class="col-sm-6 col-md-9">
        add something to display
    </div>
    <div class="col-sm-6 col-md-3">
        <h1>Enquiry</h1>
        <form role="form" action="" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock container %}

templates/home/home.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}

{% block navbar %}
<ul class="nav navbar-nav nav-tabs">
    <li class="active"><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'about' %}">About</a></li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown">Services
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          {% for service in services %}
          <li><a href="{{ service.get_absolute_url }}">{{ service.service_name }}</a></li>
          {% empty %}
          <li>Empty</li>
          {% endfor %}
        </ul>
      </li>
    <li><a href="{% url 'contact' %}">Contact Us</a></li>
    <li><a href="{% url 'appointment:book_appointment' %}">Book an Appointment</a></li>
</ul>
{% endblock navbar %}


{% block footer %}
<div class="row">
    <div class="col-sm-6 col-md-9">
        add something to display
    </div>
    <div class="col-sm-6 col-md-3">
        <p>Have something to say?</p>
        <h3><a href="{% url 'contact' %}">Enquiry/Feedback</a> </h3>
    </div>
</div>
{% endblock footer %}

templates/profile.html
{% extends 'base.html' %}

{% block container %}
<div class="page-header">
    <h1>{{ user.username }} Profile's</h1>
</div>
This is profile page

{% endblock container %}